### ISSUE TITLE
NNNNNNN's in Shovill assemblies?

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/shovill#100]
Using Shovill 1.0.4 (via Bioconda) and notice that several of my E. coli assemblies have strings of N's, as if the scaffold of SPAdes is used instead of the contigs assembly. How can I avoid that? Don't see an option there, is different from previous behaviour?

**Comment by andersgs** [comment]
Are the Ns in the FASTQ files?

**Comment by dutchscientist** [comment]
No, several files were done with earlier version and assembled fine.

According to Torsten on twitter, this may be due to something in SPAdes that may have changed.

**Comment by dutchscientist** [comment]
OK, problem turned out to be specific for SPAdes v. 3.12.0. Update to 3.13.0 has solved it.
