### ISSUE TITLE
Minimum contig coverage cuttoff "--mincov"

### ISSUE THREAD

**Issue by MostafaYA** [tseemann/shovill#102]
Hi, 
the `--mincov` option within shovill, is this describing the depth of the reads when mapped back to the contigs? or the coverage that reported in the fasta headers as for spades (kmer coverage)?

Thanks,

**Comment by rpetit3** [comment]
Hi @MostafaYA, `--mincov` is describing the coverage reported in the FASTA headers of the assembly. Here is where the filtering occurs: https://github.com/tseemann/shovill/blob/master/bin/shovill#L357:L370

**Comment by MostafaYA** [comment]
Thanks!
