### ISSUE TITLE
SPAdes memory limit error 

### ISSUE THREAD

**Issue by salvoc81** [tseemann/shovill#11]
SPAdes crashed with a malloc error due to not enough memory
It works when the memory is increased through the --memory parameter in SPAdes
Maybe it would  a possible solution to add a  --memory parameter to the Shovill pipeline

System information:
Linux version 3.10.0-327.13.1.el7.x86_64 (Red Hat 4.8.5-4)

**Comment by tseemann** [comment]
What organism are you trying to assemble?
And what coverage do you have?

**Comment by salvoc81** [comment]
Hello Torsten. It is an Ecoli isolate.
Cannot tell you about the coverage since I have properly analyzed the data.
Also I have not preprocessed data (adaptor and quality trimming) when I tried.
I will let you know I will have to better analyze the data.

Thanks for your help

**Comment by tseemann** [comment]
@salvoc81 I added a `--ram` option in 4e8b756f01d673bc6646c96e020a5ce004449dba which defaults to 32G but you can make it higher. It will work for all the tools not just Spades.
