### ISSUE TITLE
lesscpus variable is always going to be 1?

### ISSUE THREAD

**Issue by andersgs** [tseemann/shovill#110]
I am just looking over the code, and it seems to me that `lesscpus` will always be one:

```
my $lesscpus = min(1, max(4, int($cpus/4))); 
```

**Comment by tseemann** [comment]
I have no idea what I was trying to do with that line!

I think i was wanting to allocate about 25% of the total CPUs to the sorting step, but need at least 1, and the rest can be over-provisioned to the bwa mem step.

Changed to this:
```
my $sort_cpus = max( 1, int($cpus/4) );
```
