### ISSUE TITLE
MIN_RAM should be at least 2

### ISSUE THREAD

**Issue by andersgs** [tseemann/shovill#111]
MIN_RAM should be at least 2, otherwise `half_ram` becomes 0 (this is related to issue #77). Although, pilon seems to recommend at least 8GB (from pilon docs):

> 8GB or more memory to allocate to the JVM. The amount of memory required depends on the genome, the read data, and how many fixes Pilon needs to make. Generally, bacterial genomes with ~200x of Illumina coverage will require at least 8GB, though 16GB is recommended.

Nevertheless, the issue of allowing less than 2GB of RAM currently has a cascading effect downstream:

```
my $half_ram = int($ram / 2);
```

Which then causes `sort_ram` to be zero:

```
my $sort_ram = int($half_ram * 1024 / $lesscpus); # RAM per thread, in Mb
```

**Comment by tseemann** [comment]
I have added in extra checks to ensure this doesn't happen again, and increased MIN_RAM to 4 GB.
