### ISSUE TITLE
Conda3 install does not do megahit_toolkit; shovill does not work

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/shovill#112]
[shovill] This is shovill 1.0.4
[shovill] Written by Torsten Seemann
[shovill] Homepage is https://github.com/tseemann/shovill
[shovill] Operating system is linux
[shovill] Perl version is v5.26.2
[shovill] Machine has 2 CPU cores and 23.54 GB RAM
[shovill] Using bwa - /home/vetschool/miniconda3/bin/bwa | Version: 0.7.17-r1188
[shovill] Using flash - /home/vetschool/miniconda3/bin/flash | FLASH v1.2.11
[shovill] Using java - /home/vetschool/miniconda3/bin/java | openjdk version "1.8.0_192"
[shovill] Using lighter - /home/vetschool/miniconda3/bin/lighter | Lighter v1.1.2
[shovill] Using mash - /home/vetschool/miniconda3/bin/mash | 2.1.1
[shovill] Using megahit - /home/vetschool/miniconda3/bin/megahit | MEGAHIT v1.2.6
[shovill] Could not find 'megahit_toolkit' - please install it.

conda install prokka
Collecting package metadata (current_repodata.json): done
Solving environment: done
# All requested packages already installed.

Minoconda3 install of Shovill, seems to not install megahit_toolkit, and refuses to function without it. Have tried specifying the assembler as spades, no dice.

**Comment by dutchscientist** [comment]
OK, solved it for now by downgrading Megahit to version 1.1.1, which is in the Anaconca repositories and still has the toolkit.

conda install -c bioconda megahit=1.1.1

But any general upgrade will screw this up again.

**Comment by tseemann** [comment]
Please file an issue at the bioconda website and ask them to set the dependency to `megahit<=1.1.1`

**Comment by dutchscientist** [comment]
Will do at Megahit, have not had time yet.

No, I looked in the source of the new Megahit versions, and there is no toolkit that I can see.

I run Shovill default in Conda, so just standard "conda install --yes shovill". Has worked before (and really well, I love shovill!)

**Comment by dutchscientist** [comment]
Good news, I think? 

https://github.com/voutcn/megahit/issues/226#issuecomment-515272358

**Comment by tseemann** [comment]
Thanks @dutchscientist - this is excellent news.

**Comment by dutchscientist** [comment]
Not sure what to do with the Bioconda request; depends on how quick the change in BioHit is effected?

**Comment by dutchscientist** [comment]
Thanks, @andersgs and @dpryan79, have just updated my Conda/Shovill and now it passes the check with 1.2.7. Very pleased with this :)
