### ISSUE TITLE
Q: spades' "contigs.fa" contigs or scaffolds?

### ISSUE THREAD

**Issue by sklages** [tseemann/shovill#113]
I am currently struggling with some yeast PE75 datasets. `spades` seems to yield a reasonable assembly (as does MIRA). 
I am wondering where to find the scaffolded contigs?   I understand that  `contigs.fa` is the corrected contig file of the assembly. Or does `spades` omit scaffolding with just  a single PE library?

**Comment by tseemann** [comment]
Shovill does not keep the scaffolds. For most Illumina PE data they are usually identical, as the PE span is not sufficient to bridge repeats in the graph to make any difference. I feel some of the joins it makes are false, and i prefer to err on the side of conservative.

If you want the spades output files, you can get them using this option, but they won't be post-corrected.

```
  --keepfiles     Keep intermediate files (default: OFF)
```
