### ISSUE TITLE
shovill: trimmomatic error in galaxy

### ISSUE THREAD

**Issue by mushalallam** [tseemann/shovill#114]
Hi,
am getting belwo error when using shovill in galaxy,
seem trimmomatic can't read .dat files in galaxy
please advise.
Thanks

[mash] Estimated genome size: 5.64029e+06
[mash] Estimated coverage:    22.203
[mash] Writing to /tmp/0I09ZhK1Ys/sketch.msh...
[trimmomatic] Picked up _JAVA_OPTIONS:  -Xmx4g
[trimmomatic] TrimmomaticPE: Started with arguments:
[trimmomatic]  -threads 1 -phred33 /media/60tb/src/galaxy/database/files/000/dataset_593.dat /media/60tb/src/galaxy/database/files/000/dataset_594.dat R1.fq.gz /dev/null R2.fq.gz /dev/null ILLUMINACLIP:/media/60tb/src/galaxy/database/dependencies/_conda/envs/__shovill@1.0.4/db/trimmomatic.fa:1:30:11 LEADING:3 TRAILING:3 MINLEN:30 TOPHRED33
[trimmomatic] Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'
[trimmomatic] Using PrefixPair: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
[trimmomatic] Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
[trimmomatic] Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
[trimmomatic] Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'
[trimmomatic] Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
[trimmomatic] Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT'
[trimmomatic] Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'
[trimmomatic] Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
[trimmomatic] Using Long Clipping Sequence: 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
[trimmomatic] Using Long Clipping Sequence: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT'
[trimmomatic] Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'
[trimmomatic] Using Long Clipping Sequence: 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
[trimmomatic] Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
[trimmomatic] Using Long Clipping Sequence: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
[trimmomatic] ILLUMINACLIP: Using 2 prefix pairs, 17 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
[trimmomatic] **Exception in thread "main" java.lang.RuntimeException: Invalid FASTQ name** line: �Խ�r�8�u{��bGԍ�rU�,��u}���+���cL�e��ٽ�{�M�$$@Ήx>���l5���EUO���y����kb�W����N��gZ�QO������v�w�OV�������3q�9����G���o�d!�Ԓ���7��s��D����ѕ��9Si���v�S�=���@��9�A����p��~C0�����="������tE���}���5�˵��ps�R�������Ү겭/m^S�#;_*�X*v�|�._���͡��l�^������_$Y-�_��-Y_KeV_Ƌc��v�j<���0��LvL�;���~��|�'ˠ
[trimmomatic] 	at org.usadellab.trimmomatic.fastq.FastqParser.parseOne(FastqParser.java:68)
[trimmomatic] 	at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:164)
[trimmomatic] 	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:265)
[trimmomatic] 	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:555)
[trimmomatic] 	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
[lighter] ERROR: Could not access file R1.fq.gz
[FLASH] ERROR: Failed to open "R1.cor.fq.gz" for reading: No such file or directory
[FLASH] FLASH did not complete successfully; exiting with failure status (1)
[spades] 
[spades] 
[spades] == Error ==  file not found: /media/60tb/src/galaxy/database/jobs_directory/000/186/working/out/flash.notCombined_1.fastq.gz (left reads, library number: 1, library type: paired-end)
[spades] 
[spades] In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
[spades] or report an issue on our GitHub repository github.com/ablab/spades
[spades] Please provide us with params.txt and spades.log files from the output directory.

**Comment by tseemann** [comment]
I have no power over the galaxy wrapper.
It also will depend on _which_ Galaxy server you are running it on.
Please contact the administrators of that Galaxy server.
@slugger70

**Comment by pvanheus** [comment]
@tseemann I think I know what's going on here. @mushalallam enabled the `--trim` option, which means that `shovill` runs: 

`trimmomatic PE -threads 1 -phred33 BLAH/dataset_18319.dat BLAH/dataset_18305.dat R1.fq.gz /dev/null R2.fq.gz /dev/null ILLUMINACLIP:BLAH/db/trimmomatic.fa:1:30:11 LEADING:3 TRAILING:3 MINLEN:30 TOPHRED33 2>&1 | sed 's/^/[trimmomatic] /' | tee -a shovill.log`

which means that Trimmomatic incorrectly assumes these are uncompressed fastq and the error results. This issue has in fact been reported on the Galaxy `tools-iuc` side:

https://github.com/galaxyproject/tools-iuc/issues/1804

I'll make sure Björn's suggested fix is implemented.
