### ISSUE TITLE
Number of CPUs defaults to number of cores is not a good default

### ISSUE THREAD

**Issue by andersgs** [tseemann/shovill#115]
This is probably a bad default. On our system, this defaults to 72 CPUs, which invariably causes an IO issue with Spades.

Perhaps a safer bet might be to have `num_cpus` return something like `min(8, n_cpus)`. 

In addition, an exception could perhaps be raised if the user tries to run shovill with spades and too many CPUs.

**Comment by tseemann** [comment]
The IO issues are related to `ulimit` on number of open files. 
Upstream won't reduce their file needs: https://github.com/ablab/spades/issues/120
I think reducing it is a good idea.
