### ISSUE TITLE
spades.fasta is not discovered on time on the slow I/O disks

### ISSUE THREAD

**Issue by kbessonov1984** [tseemann/shovill#118]
I found by accident a small bug that prevents successful completion of the shovill pipeline using spades as the default assembler. I've tried to assemble genomes on a remote drive that is know to be laggy and all assemblies failed with the `Can not see spades.fasta file to correct!`. The same sample was successfully assembled on a faster local drive. 

I suggest addition of a wait time (e.g. 5 seconds) before the `spades.fasta` check step to accommodate slower systems. In addition, it would be nice to have a resume functionality in cases of accidental crash or memory error.

**Comment by tseemann** [comment]
I'm not sure how that is even possible. There is laggy, and there is buggy mount settings. Unix would not allow such a thing to happen.  How is that drive mounted? Is it NFS or CIFS ?

I am not going to add a 5 second delay. You can resolve it by using `--tmpdir` to point to a fast local disk instead of using the slow disk. This is affected by your system env-var `$TMPDIR` too.

Mine says this:
```
%  shovill --help |& grep tmpdir
  --tmpdir XXX    Fast temporary directory (default: '/tmp/tseemann')
```

**Comment by tseemann** [comment]
As for "In addition, it would be nice to have a resume functionality in cases of accidental crash or memory error." you'll need to file a separate issue.

**Comment by kbessonov1984** [comment]
Thank you for clarification of the `--tmpdir` parameter. Mine has no default value and needs to be explicitly specified.
```
(shovill) [kbessono@jupyter kbessono]$ shovill --help |& grep tmpdir
  --tmpdir XXX    Fast temporary directory (default: '')
```
I think our system is NFS for the mounted drives. I've also solved this issue by temporarily copying fastq input files and then moving entire shovill output directory to the mounted directory. In the future I will make use of `--tmpdir` parameter.

**Comment by tseemann** [comment]
Our system is also NFS, here is out `mount` settings:
```
/home on /home type nfs4 (rw,noatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=rdma,port=20049,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.12,local_lock=none,addr=192.168.1.2)
```

**Comment by tseemann** [comment]
If you don't have a `--tmpdir` set it will fall back to system `tempdir()` function which will likely be `/tmp` which is not NFS usually, so it should work. 

```
$tmpdir ||= File::Temp->newdir(CLEANUP=>1);
```
Are you on `shovill 1.0.8` ?

**Comment by kbessonov1984** [comment]
I am using shovill version`1.0.9`. Our system admin confirmed that our shared drive is not fast as it has many directories and has very open access permissions which might be and issue. 
I've tired to use `--tmpdir` switch, and it helped. 

```
%shovill --R1 SRR5666384_1.fastq --R2 SRR5666384_2.fastq --cpus 32 --tmpdir /tmp -outdir  shovill
[spades] Other parameters:
[spades]   Dir for temp files: /tmp
[spades]   Threads: 32
[spades]   Memory limit (in Gb): 32
...
[shovill] Repaired 5 contigs from spades.fasta at 5 positions.
[shovill] Removing low coverage contig (< 2 x): NODE_107_length_1769_cov_1.835566_pilon
[shovill] Removing low coverage contig (< 2 x): NODE_143_length_944_cov_1.478580_pilon
[shovill] Removing low coverage contig (< 2 x): NODE_196_length_632_cov_0.960396_pilon
[shovill] Removing homopolymer-128G contig: NODE_411_length_128_cov_2230.000000_pilon
[shovill] Assembly is 5414300, estimated genome size was 5412490 (+0.03%)
[shovill] Using genome graph file 'spades/assembly_graph_with_scaffolds.gfa' => 'contigs.gfa'
[shovill] Walltime used: 8 min 10 sec
[shovill] Results in: /Drives/T/PathogenBiology/ectyper_benchmarking/test/shovill
[shovill] Final assembly graph: /Drives/T/PathogenBiology/ectyper_benchmarking/test/shovill/contigs.gfa
[shovill] Final assembly contigs: /Drives/T/PathogenBiology/ectyper_benchmarking/test/shovill/contigs.fa
[shovill] It contains 409 (min=105) contigs totalling 5414300 bp.
[shovill] Remember, genomic repeats > ~800bp will be collapsed into single contigs.
[shovill] Done.
```

**Comment by tseemann** [comment]
@kbessonov1984 i'm glad you found a solution. thank you for getting back to me.
