### ISSUE TITLE
Error: Wrong input file!

### ISSUE THREAD

**Issue by allebiotech** [tseemann/shovill#120]
Dear @tseemann,

I'm running Shovill 0.9.0 with KMC 3.1.0. It worked with all my fastq files except for two cases, where the 20-kmc.log file says: ************Error: Wrong input file!

The command was:  shovill --force --outdir  --minlen 150 --R1 fastq.gz --R2 fastq.gz

What should I do?

Thank you in advance!

**Comment by tseemann** [comment]
You should upgrade to 1.0.8 
`kmc` is not used anymore

**Comment by allebiotech** [comment]
Thank you a lot. It works now!


Il giorno mer 13 nov 2019 alle ore 03:05 Torsten Seemann <
notifications@github.com> ha scritto:
