### ISSUE TITLE
mash/2.1 breaks shovill

### ISSUE THREAD

**Issue by EricDeveaud** [tseemann/shovill#122]
using mash/2.0 shovill runs correctly, but using mash/2.1 it breaks with following error message.

```
[shovill] Running: mash sketch -o /tmp/eBSfbosO18/sketch -p 8 -k 32 -m 3 -r \/mount\/gensoft2\/tests\/shovill\/1\.0\.0\/\.\.\/\.\.\/datas\/Shovill\/R1\.fq\.gz 2>&1 | sed 's/^/[mash] /' | tee -a shovill.log
[mash] ERROR: The option p cannot be used with r.
[shovill] Could not determine genome size from ''
```

but you already knew it: https://github.com/marbl/Mash/issues/99

maybee include a note in the readme, or tag the version to use and to not use ;-)

Eric

**Comment by tseemann** [comment]
I think you may need to upgrade to `shovill 1.0.8` maybe?

**Comment by phiweger** [comment]
nope, still breaks @tseemann 

```bash
[shovill] Could not determine genome size from ''
mash --version
# 2.2.2
shovill --version
# shovill 1.1.0
```

**Comment by tseemann** [comment]
@phiweger shovill 1.1.0 doesn't use mash anymore. it uses kmc. provide `--gsize` and you don't need either.
