### ISSUE TITLE
Multiple libraries assembly

### ISSUE THREAD

**Issue by DomeJoyce** [tseemann/shovill#123]
Reading your manual, it's seems that users can use only one paired-end library at run. Since most of genome assembly project are projected starting with 2 or more libraries constructed with different insert size, is it possible to add this function in order to use all libraries in one single run? 
Spades gives the possibility to use different libraries (up to 9 for each run), so if any library is given as --R1-1 --R1-2 --R2-1 --R2-2 is would be great!
Please correct me if i misunderstand it, and thanks for your work.

**Comment by tseemann** [comment]
Shovill is for bacteria only. 

Mate-pair libraries are rarely used in bacterial genomics. They never worked well in the past, and have been supplanted by long reads now.

If you want to use more complicated steps that PE R1 + R2 then please use Spades directly.
