### ISSUE TITLE
How to handle the huge CPUs and Memory?

### ISSUE THREAD

**Issue by indexofire** [tseemann/shovill#124]
Spades will be stopped with error like "Error in malloc(): out of memory. Requested: 144176, active: ..." if I set up for example, --memory 400 --cpus 160, on my 160 cores and 512G mem machine. 

When I changed to --memory 32 --cpus 16, the assembly is fine. Any recommendation of memory and cpus settings on machine like this? Or should I spliced assembling genomes into parallel jobs?

**Comment by tseemann** [comment]
That error is from `spades` not from Shovill. 
It's been documented before with no proper resolution: https://github.com/ablab/spades/issues/56

If you are doing more than one assembly, you are much better off running 5 of them at once with 32 threads each, or even 10 with 16 threads each.

**Comment by indexofire** [comment]
thanks!

**Comment by sk-sahu** [comment]
Yes, this certainly an issue with spades. I'm using shovill-v1.1.0  with provided `--ram` option comes up with following issues. Otherwise just removing the memory limit works fine.

```
[spades]   0:00:18.883   830M / 2G    ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12

 finished abnormally, OS return value: 255
```
