### ISSUE TITLE
--isolate option introduced in SPAdes 3.14.0

### ISSUE THREAD

**Issue by fengyuchengdu** [tseemann/shovill#125]
Hi Torsten,
I noticed a warning 
"== Warning ==  No assembly mode was sepcified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option." 
in the shovill log file after updating to SPAdes 3.14.0 and I am wondering if I should add this "--isolate" option with "--opts", given that this "--isolate" flag is not compatible with "--careful".
Many thanks

**Comment by tseemann** [comment]
Shovill does not use the `--careful` flag; it does its own error correction using `pilon`.

The `--isolate` option seems to work well, I will look to add support for it.
