### ISSUE TITLE
formatting java dependencies.

### ISSUE THREAD

**Issue by Phylloxera** [tseemann/shovill#126]
How to install pilon/trimmomatic so I don't get:
> [shovill] Using pilon - /bin/pilon | sh: 1: pilon: Exec format error

I am currently doing `unzip Trimmomatic-0.39.zip; rm Trimmomatic-0.39.zip; mv Trimmomatic-0.39/trimmomatic-0.39.jar /bin/trimmomatic; chmod +x /bin/trimmomatic`

also btw kmc not on your dependency list. Thanks, Aaron

**Comment by tseemann** [comment]
You need to have a shell wrapper script for pilon and trimmomatic. You can't rename a .jar file and expect it to run. If you use brew or bioconda this will be done for you. But in the simplest case you can make one:

```
#!/bin/sh
exec java -jar /path/to/pilon.jar $*
```

I forgot to replace mash with kmc in the dep docs - thank you i have fixed it.
