### ISSUE TITLE
SPAdes err code: -6 when shovill sub-sample option is enabled

### ISSUE THREAD

**Issue by eam12** [tseemann/shovill#127]
Hello! I noticed that when I run shovill using the default `--depth 100` option some of the assemblies fail with the `SPAdes err code: -6` and the message `'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'`. I've read about this error on the SPAdes GitHub page (e.g. such as [here](https://github.com/ablab/spades/issues/104)) and as I understand it, for some reason my sequencing was uneven across the genome.

I noticed that when I run shovill disabling the subsampling (`--depth 0`), SPAdes seems to run successfully. However, I'm not sure I fully understand why *not* subsampling would fix this issue. Wouldn't downsampling to a maximum of 100X make coverage *more* even across the genome? Any insight would be very much appreciated.

**Comment by tseemann** [comment]
If your coverage is uneven then subsampling keeps it uneven; there is just less of it overall. the subsampling does not know about the genome or user any kmer information --- that is called "digitial normalization" and has its own suite of issues.

The default in 1.1.0 is now 150 and it uses Spades new --isolate mode.

However if it is truly non-uniform (why?) then use `spades.py --sc` mode directly and don't use shovill.

**Comment by eam12** [comment]
Many thanks for your advice!
