### ISSUE TITLE
how we can concatenate the contigs in the output

### ISSUE THREAD

**Issue by mabouelk** [tseemann/shovill#128]
Hi @tseemann ,
Shovill is working well with me but when I import the output (contigs.fa) into another tool, I found the output consist of so many individual contigs. How can I concatenate them or  label them individually by the isolate name so I can recognize them when I do further analysis?

**Comment by tseemann** [comment]
All genome assemblies will be in multiple pieces. Artificially joining them into a single DNA sequence is risky because it introduces false joins. 

You can rename a FASTA file using
```
seqtk rename old.fasta ECOLI200_ > new.fasta
```

If you really really want a single sequence:
```
echo ">SEQNAME" > new.fasta
grep -v '>' old.fasta >> new.fasta
```
