### ISSUE TITLE
bwa option -x intractg is likely incorrect

### ISSUE THREAD

**Issue by tolot27** [tseemann/shovill#13]
The bwa mem option `-x intractg` is used to map intra-species contigs to the the reference. Mapping the initial reads, `-x intractg` should not be used in the pilon step, IMHO.

**Comment by tseemann** [comment]
Using reads for correction is different to using reads for alignment to something 'similar'. Here, the assembly was generated from the same reads, so a priori we expect very few changes. The `intractg` setting was a convenient way to penalise SNPs and Indels more than default:

Default is `-B 4 -O 6 -L 5` and  `intractg: -B9 -O16 -L5  (intra-species contigs to ref)`.

That was my rationale, but it's not clear what is best, and not using it as you suggest would probably not affect the results.
