### ISSUE TITLE
bioboxes docker image is out of date (shovill v0.7.1)

### ISSUE THREAD

**Issue by kapsakcj** [tseemann/shovill#130]
Hi Torsten,

I noticed that the link on the README links to a bioboxes docker image which has shovill v0.7.1 specified.

StaPH-B has a docker image available for 1.1.0 and 1.0.4 if you'd like to direct users there (with a disclaimer that you don't maintain the docker images)

Following suit from the prokka README:
```
docker pull staphb/shovill:latest
docker run staphb/shovill:latest shovill --help

singularity build shovill.sif docker://staphb/shovill:latest
singularity exec shovill.sif shovill --help
```
* docker image repo: https://hub.docker.com/r/staphb/shovill
* dockerfile for shovill 1.1.0: https://github.com/StaPH-B/docker-builds/blob/master/shovill/1.1.0/Dockerfile

Shovill is by far our most downloaded docker image :) 

Curtis

**Comment by tseemann** [comment]
Fixed => https://github.com/tseemann/shovill#containers

I am planning to systematically go through all my tools and refer container installation to your awesome StaPH-B repo - thank you for all that work!

**Comment by kapsakcj** [comment]
Awesome!!

Thank you for developing such amazing tools 😃
