### ISSUE TITLE
Parameter missing in biconda

### ISSUE THREAD

**Issue by Ankita-1211** [tseemann/shovill#131]
some parameters missing like ASSEMBLER choice when i install using biconda

**Comment by tseemann** [comment]
What version did you install in Bioconda?
```
nullarbor --version
nullarbor --check
```

**Comment by Ankita-1211** [comment]
shovill 0.9.0

**Comment by tseemann** [comment]
yes, that one is > 2 years old!
`v0.9.0 tseemann released this on 2 Mar 2018`
