### ISSUE TITLE
shovill got stucked at kmc stage

### ISSUE THREAD

**Issue by fengyuchengdu** [tseemann/shovill#133]
I've been using shovill for a while and found that this happened randomly, and a simple re-run would always fix the problem but it is really annoying especially when a task could have finished by Monday. Is there anything I can do to avoid this ? Many thanks.

############## log ################

[shovill] Hello zong
[shovill] You ran: /home/zong/anaconda3/envs/torsten/bin/shovill --trim --cpus 34 --ram 128 --minlen 200 --R1 /media/zong/HDD/kp_genbank/1/fastq/DRR076952_1.fastq --R2 /media/zong/HDD/kp_genbank/1/fastq/DRR076952_2.fastq --outdir /home/zong/SSD_temp/shovill/20200516122227/3aZxuwNibf/DRR076952_quick_shovill
[shovill] This is shovill 1.1.0
[shovill] Written by Torsten Seemann
[shovill] Homepage is https://github.com/tseemann/shovill
[shovill] Operating system is linux
[shovill] Perl version is v5.26.2
[shovill] Machine has 36 CPU cores and 251.38 GB RAM
[shovill] Using bwa - /home/zong/anaconda3/envs/torsten/bin/bwa | Version: 0.7.17-r1188
[shovill] Using flash - /home/zong/anaconda3/envs/torsten/bin/flash | FLASH v1.2.11
[shovill] Using java - /home/zong/anaconda3/envs/torsten/bin/java | openjdk version "1.8.0_192"
[shovill] Using kmc - /home/zong/anaconda3/envs/torsten/bin/kmc | K-Mer Counter (KMC) ver. 3.1.1 (2019-05-19)
[shovill] Using lighter - /home/zong/anaconda3/envs/torsten/bin/lighter | Lighter v1.1.2
[shovill] Using megahit - /home/zong/anaconda3/envs/torsten/bin/megahit | MEGAHIT v1.2.9
[shovill] Using megahit_toolkit - /home/zong/anaconda3/envs/torsten/bin/megahit_toolkit | v1.2.9
[shovill] Using pigz - /home/zong/anaconda3/envs/torsten/bin/pigz | pigz 2.3.4
[shovill] Using pilon - /home/zong/anaconda3/envs/torsten/bin/pilon | Pilon version 1.23 Mon Nov 26 16:04:05 2018 -0500
[shovill] Using samclip - /home/zong/anaconda3/envs/torsten/bin/samclip | samclip 0.4.0
[shovill] Using samtools - /home/zong/anaconda3/envs/torsten/bin/samtools | Version: 1.10 (using htslib 1.10.2)
[shovill] Using seqtk - /home/zong/anaconda3/envs/torsten/bin/seqtk | Version: 1.3-r106
[shovill] Using skesa - /home/zong/anaconda3/envs/torsten/bin/skesa | SKESA v.2.3.0
[shovill] Using spades.py - /home/zong/anaconda3/envs/torsten/bin/spades.py | SPAdes genome assembler v3.14.0
[shovill] Using trimmomatic - /home/zong/anaconda3/envs/torsten/bin/trimmomatic | 0.39
[shovill] Using velvetg - /home/zong/anaconda3/envs/torsten/bin/velvetg | Version 1.2.10
[shovill] Using velveth - /home/zong/anaconda3/envs/torsten/bin/velveth | Version 1.2.10
[shovill] Found spades version: 003014000
[shovill] Will use spades 003014000 options: --isolate and --merged
[shovill] Using tempdir: /tmp/gDWxNEDUcH
[shovill] Changing into folder: /home/zong/SSD_temp/shovill/20200516122227/3aZxuwNibf/DRR076952_quick_shovill
[shovill] Collecting raw read statistics with 'seqtk'
[shovill] Running: seqtk fqchk -q3 \/media\/zong\/HDD\/kp_genbank\/1\/fastq\/DRR076952_1\.fastq >/tmp/HdFPvVlLWm 2>&1 | sed 's/^/[seqtk] /' | tee -a shovill.log
[shovill] Read stats: max_len = 301
[shovill] Read stats: total_bp = 368479096
[shovill] Read stats: min_len = 35
[shovill] Read stats: avg_len = 287
[shovill] Estimating genome size by counting unqiue 21-mers > frequency 10 
[shovill] Running: kmc -sm -m64 -t34 -k21 -ci10 \/media\/zong\/HDD\/kp_genbank\/1\/fastq\/DRR076952_1\.fastq /tmp/ybkvybiFtW/kmc /tmp/ybkvybiFtW 2>&1 | sed 's/^/[kmc] /' | tee -a shovill.log

**Comment by tseemann** [comment]
if it happens randomly, the problem is kmc or your system
conda kmc sometimes has problem i don't know why
do you have enough free space on /tmp drive? kmc needs that
i run shovill on DRR076952 with -m 128 and -t 34 ok
i wonder if .fastq vs .fastq.gz causes problems with kmc

**Comment by indexofire** [comment]
In my experience, it happened in different computers in ubuntu and archlinux. and it looks like nothing about the data. after killing the process of kmc and rerun it, it will be fine sometimes. so maybe it is about conda because I install shovill from conda in every environment.
