### ISSUE TITLE
`Error 34304 running command` when the kmc part of the pipeline is running

### ISSUE THREAD

**Issue by michaelbarton** [tseemann/shovill#14]
I get the following output at the kmc part of the pipeline. 

```
Estimating genome size with 'kmc'
Running: kmc -ci3 -k25 -t1 \/tmp\/tmp\.q0ZexVtdJO\.fq\.gz kmc /tmp >> 20-kmc.log 2>&1
Error 34304 running command
```

The contents of 20-kmc.log are:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**Comment by michaelbarton** [comment]
I am building a docker image here:

https://github.com/bioboxes/shovill/tree/release/0.3

**Comment by michaelbarton** [comment]
I also get this for 0.4 version of shovill too.

**Comment by tseemann** [comment]
@michaelbarton which version of kmc are you using?

```
kmc --help
K-Mer Counter (KMC) ver. 3.0.0 (2017-01-28)
```

That C++ error used to happen with `freebayes` a lot too...

**Comment by michaelbarton** [comment]
We're using 3.0.1. We're creating a Docker image and the versions of each
tool are here:

https://github.com/bioboxes/shovill/blob/release/0.4/Dockerfile

**Comment by andersgs** [comment]
@michaelbarton do you get the same problem if you use a different base image, say ubuntu:latest? 
Are you able to run an interactive session, and run KMC?

**Comment by michaelbarton** [comment]
Thanks for following up, I get the same error using an interactive (docker
-it) session. I haven't tried ubuntu, however we use the same debian biobox
base image in our other assembler Docker images.

**Comment by michaelbarton** [comment]
Are there minimum memory requirements for running KMC? I'm testing this in a
1gb virtual machine.

**Comment by tseemann** [comment]
@michaelbarton yes, manty of the components of shovill need > 1 GB RAM includign KMC:

```
kmc -h | grep RAM
  -m<size> - max amount of RAM in GB (from 1 to 1024); default: 12
  -r - turn on RAM-only mode
```
Spades also defaults to 250 GB (I set it at 32 GB).

I could make a parameter to Shovill for --ram and make *some* attempt to set it per command. But 1 GB might be pushing it for a bacterial genome assembly, unless the reads were VERY clean.

**Comment by michaelbarton** [comment]
Thanks Torsten, that's probably it. I'm only testing this on a small set of
reads on a small VM to make sure everything is installed correctly. Usually
we'd use a 64gb or 128gb node in production. I should be able to set this
dynamically for kmc based on how much memory is available to the docker
image.

**Comment by michaelbarton** [comment]
It looks like the memory usage was the issue. I was able to get this to run by dynamically setting kmc's memory - https://github.com/bioboxes/shovill/commit/7070760dd58befc379c8939fef298e0d7be02322.

**Comment by michaelbarton** [comment]
I this was originally setting pilon's memory dynamically too. I can't remember if I wrote this or it was bundled with pilon.

https://github.com/bioboxes/shovill/blob/master/image/bin/pilon

If you would like like to combine both the memory parameters for  kmc and pilon in future versions, that would certainly be useful. In the meantime, I think this docker images works for 0.4 now.

**Comment by rec3141** [comment]
I solved this issue with `ulimit -n 2048` as per https://github.com/sanger-pathogens/iva/issues/63

**Comment by tseemann** [comment]
@rec3141 thanks for the info -- every linux system has a different "file open" limit. Ours in 2048, but can be extended to 4096 maximum.
