### ISSUE TITLE
—depth downsampling

### ISSUE THREAD

**Issue by mmaesaar** [tseemann/shovill#146]
I have a quick question. When —depth is downsampled to 150x is this 150x the correct coverage to report in the manuscript?

**Comment by mmaesaar** [comment]
I rechecked the shovill.log there are coverage in many places - any good suggestions which one to use to report the sequencing coverage are welcome?

Thank you

**Comment by mmaesaar** [comment]
Any suggestions?

**Comment by andersgs** [comment]
@mmaesaar there are two things here. The first is the depth of coverage that you sequenced at, which maybe above 150X, and may be influenced by your study design. And the second is the sequencing effort, so how much did you cover your genome of interest. Say you are interested in mix colony population and you deep sequenced your isolates. However, that deep sequencing presents a problem for assembly algorithms relying on the de Bruijn graph. So, you downsample. 

What you report, therefore, has to make sense from the context of the study. 

In general, I would report that the sequences were downsampled to 150X for assembly using shovill. But, for general sequencing stats, I would report the sequencing effort. Which could be as simple as the number of sequenced nucleotides that pass QC divided by the expected genome size. Or you could use a tool like mash to calculate the coverage based on the estimated genome size obtained from an analysis of the number of kmers.

**Comment by mmaesaar** [comment]
Great answer @andersgs ! I really appreciate the time you took to answer my question thoroughly.

**Comment by asl** [comment]
FWIW, deep sequencing does not present any problem for assembly algorithms relying on the de Bruijn graph per se. For OLC - yes, this is a big problem.
