### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by rec3141** [tseemann/shovill#15]
On MacOSX, after 
`brew tap homebrew/science` and `brew tap tseemann/bioinformatics-linux` complete successfully, `brew install shovill` fails with 

```
Error: No available formula with the name "shovill"
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by tseemann** [comment]
That is unexpected.  
Is your brew installation in a good state?
What does `brew doctor` say?

**Comment by rec3141** [comment]
is the recipe supposed to be in homebrew-science or tseemann/bioinformatics-linux or somewhere else? I don't see it in either of those repos

**Comment by tseemann** [comment]
#rec3141 I owe you an aplogy! It seems i did not push my changes to github recently!
Sorry about that. I have pushed them now.

Try `brew update && brew install shovill`

**Comment by rec3141** [comment]
installed! but now is missing a file

`Can't see adapter file: /usr/local/Cellar/shovill/0.4/bin/../db/trimmomatic.fa`

**Comment by tseemann** [comment]
@rec3141 whoops, i forgot to add that file to the repo too. Sorry again. I've made a new 0.5 release and updated the brew package, so:

```
brew update && brew reinstall shovill
```
