### ISSUE TITLE
Shovill not using --isolate flag for spades call

### ISSUE THREAD

**Issue by franciscozorrilla** [tseemann/shovill#156]
If I understood correctly, `shovill` should use the `--isolate` flag by default for assembling given `spades` version >= 3.14:

https://github.com/tseemann/shovill/blob/f64d19e3fc3d0d29b1a5f6d20d10a08154f03305/bin/shovill#L448

I verified that I have at least v3.14 of `spades`:

```
$ conda list|grep -i spades
spades                    3.15.2               he641558_0    bioconda
```
Shovill does not appear to be using the `--isolate` flag:

[00-shovill.log](https://github.com/tseemann/shovill/files/6873921/00-shovill.log)
[60-spades.log](https://github.com/tseemann/shovill/files/6873922/60-spades.log)
[warnings.log](https://github.com/tseemann/shovill/files/6873923/warnings.log)

Do I need to pass the `--opts --isolates` option to the `shovill` call?

**Comment by franciscozorrilla** [comment]
OK I now see that the `--isolates` flag was introduced in version 1.1 of shovill, I was previously using version 0.9 which was installed by default using mamba for installation. I now see that the `--isolates` flag is used by default.

**Comment by tseemann** [comment]
Glad you sorted it out @franciscozorrilla !
