### ISSUE TITLE
lighter stalls when installed from homebrew

### ISSUE THREAD

**Issue by rec3141** [tseemann/shovill#16]
FYI https://github.com/mourisl/Lighter/issues/25

**Comment by tseemann** [comment]
Not really a shovill issue, but:

1. First I would try `brew reinstall lighter -s` to build from source.

2. Then try `brew install gcc && brew reinstall lighter -s`  to compile it from source with GCC instead.

**Comment by tseemann** [comment]
@rec3141 i assume you managed to resolve this? if so, may I close this issue?
