### ISSUE TITLE
memory issues

### ISSUE THREAD

**Issue by rec3141** [tseemann/shovill#17]
I'm assembling a 100Mbp genome and having memory issues with both SPAdes and Pilon. The pipeline tried to use 32Gb for SPAdes which was not enough, I had to run it manually with more. Pilon also ran out of memory, and I had to run it by hand using the jar file rather than the binary installed by homebrew, as `java -Xmx48G -jar /usr/local/Cellar/pilon/1.22/pilon-1.22.jar ...`

It would be useful to have a `--restart-from` command to pick up after a crash

**Comment by tseemann** [comment]
@rec3141 i never anticipated this be used for a 100 Mbp genome. My focus is bacterial genomes.

I recently added a `--ram` option that gets used for Spades and KMC (default 32 GB max).

However I use the Pilon wrapper script which sets the RAM inside it (I think I made it 8G). 

I believe I (and your) might be able to do `export _JAVA_OPTIONS="-Xmx48g"` before running it and it will use that option to set it, or I could call `pilon -Xmx48g` and it might use it.

if you can confirm that setting that beforehand works, I will update Shovill to do that?
Like this:
```
export  _JAVA_OPTIONS="-Xmx48g"
shovill --ram 48 --outdir XXX --R1 XXX --R2 XXX
```

Thanks!

PS. Spades 3.10 claims lower memory usage than previous versions.
