### ISSUE TITLE
Value "1.5" invalid for option ram (number expected)

### ISSUE THREAD

**Issue by michaelbarton** [tseemann/shovill#22]
Float numbers don't appear to be supported for ram, e.g. `--ram 1.5`.

**Comment by tseemann** [comment]
@michaelbarton I restricted that setting to an integer deliberately because it is passed directly onto Spades and Lighter, both of which *only* take a `GB` integer.

Options:
* accept floating point (or MB) and round down?
* accept floating point (or MB) and round up?  (risky as might exceed physical RAM)
* just document it better?

What would you need for your purposes?

**Comment by michaelbarton** [comment]
Thanks for following up Torsten. I think my use case is a relative minor one. When running shovill in a docker image there might less memory available than is available on the host computer. This could either be because it has been restricted by cgroups, or because it's being run on OSX or windows which runs docker in a virtual machine with a fixed amount of memory.

In these cases I think this should be set by shovill, rather than the user. Perhaps pick a reasonable value, say 85-90% of RAM and then pass this to the dependent tools? This could then be overridden using the `--ram` flag.

I'm testing docker images of shovill using a very small read set. This does not realistically mimic an isolate genome, which I think is the use case for shovill. It is however useful for testing all the parts have been installed in the docker image and are working as expected, if contigs are produced.

I would guess that round down is the least risky option? The only exception is if 0.8 is passed for example. Perhaps you could round down with a floor of 1? Rounding will only likely matter for small memory machines, but I could envisage cases of post docs doing assemblies on their laptops (as I did at one point in time)

Thanks again for being so responsive to issues Torsten.

**Comment by tseemann** [comment]
@michaelbarton do you know a good portable way to determine available RAM ?

**Comment by michaelbarton** [comment]
I just added this to the biobox image of shovill 0.7.1. You could use this or port a version to perl?

https://github.com/bioboxes/shovill/commit/d562bcf46dbd7e64b46ae9127cf5ba281c63950e#diff-f740bb9c5608f352b821d078267b6ed5

**Comment by tseemann** [comment]
@michaelbarton I have to support macOS too. Here is what I am using:
```
https://github.com/tseemann/shovill/commit/2d9b4be4695f6024060481e8f6c1e73d65bd6754#diff-fbc60fb02f2481d76f386d126168e315R411
```
