### ISSUE TITLE
--nocorr option fails at pilon step.

### ISSUE THREAD

**Issue by Slugger70** [tseemann/shovill#33]
When running with `--nocorr` option, shovill 0.7.1 fails and returns the following error:

```
User supplied --nocorr, so not correcting contigs.
read_file 'pilon.changes' - sysopen: No such file or directory at /home/ubuntu/miniconda3/bin/shovill line 296.
```

Commandline used: 
`shovill --outdir out_nocorr --R1 mutant_R1.fastq --R2 mutant_R2.fastq --nocorr --ram 6`

**Comment by tseemann** [comment]
Nice find! Thank you. Fixed.
