### ISSUE TITLE
Updated spades assembly parameters per spades team suggestion. 

### ISSUE THREAD

**Issue by michaelbarton** [tseemann/shovill#41]
According to spades team, the merged and unmerged reads should be treated as two separate libraries.

https://twitter.com/spadesassembler/status/907714056387252225

**Comment by tseemann** [comment]
@michaelbarton wow - thanks for letting me know. Looking at their latest manual I see
```
Do not use -s options for single-read libraries, since it specifies unpaired reads for the first paired-end library.
```
In a way, these merged reads are like orphan PE reads. In many cases they fully overlap so are no different to just providing R1 and not R2.

But the Spades team know their software and I am excited to change this in the hope it improves results even further!
