### ISSUE TITLE
Delete temp files AS YOU GO to save space

### ISSUE THREAD

**Issue by tseemann** [tseemann/shovill#45]
Currently deletes at the end,

**Comment by indexofire** [comment]
it will delete anything right? I made some mistakes before that shovill deleted all of my fastq.gz files at the end because of not apply -outdir option ...

it should be only delete temp files as a issue.

**Comment by tseemann** [comment]
@indexofire that bug was fixed in https://github.com/tseemann/shovill/commit/f04499179a2cd5c7672be5d05d4228f56a570cf1

sorry about that. i never anticipated people would use `--outdir .` !

**Comment by indexofire** [comment]
thank you @teemann , I just forgot use --outdir sometimes. :D
