### ISSUE TITLE
[Typo] "Removing short conting" + [bug?] error when running with max RAM

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/shovill#46]
Something to correct in a future version, Shovill says when removing short contigs:
"Removing short conting"

More seriously, Shovill (the Java virtual machine) crashed at the Pilon stage when I defined "--ram 20.00", and exited with error 256. Removing the RAM command from the instructions and it ran without a hitch. Not sure whether that is a bug?

Ubuntu 16.04.3 LTS, installed via Linuxbrew, in a Virtualbox computer.

**Comment by tseemann** [comment]
1. I've fixed the typo - thank you!

2. I am also getting `Error 256` on trimmomatic and pilon now too. I am investigating it. It's probably due to the `_JAVA_OPTIONS` I set, which were to ensure it didn't get killed on clusters where you have to know how much RAM you will be using.    I'm working on it. Thank for letting me know it is not just me.

**Comment by dutchscientist** [comment]
Misery and problems love company! I first switched everything to the Linuxbrew installation (some dependencies were already in usr/bin), but that did not help, only not including --ram 20.00 did.

A1: 32 Gb RAM, it is a virtualbox Ubuntu computer in a Windows 7 host with 64 Gb RAM (I wanted it dual boot, IT said no).

A2. version 1.8.0_144 & Java Hotspot server VM build 25.144-b01, mixed mode

A3:

**Comment by tseemann** [comment]
Does it really say `-mx1000m` and not `-Xmx1000m` ?

I'm thinking the `-ms20m` might be too small...   can you change it to `-Xms100m` ?

**Comment by dutchscientist** [comment]
Yes, it says "exec java -mx1000m -ms20m", not Xmx1000m.

Where do I change this?

**Comment by tseemann** [comment]
Turns out that `pilon` memory line is my work from long ago.   Looks like I messed it up. I will try and fix.

**Comment by tseemann** [comment]
Can you try `brew install brewsci/bio/pilon`  (or `reinstall`) ?

**Comment by dutchscientist** [comment]
With reinstall I now get "-Xmx1000m -Xms20m" (the rest stays the same).

When brew first updated (hadn't used it for a while), it also complains about perl being deprecated.

**Comment by tseemann** [comment]
you need to ensure you update brew regularly   `brew update`

try now `brew install brewsci/bio/shovill`

**Comment by tseemann** [comment]
I assume you fixed it.
