### ISSUE TITLE
--trusted-contigs option not enabled for spades?

### ISSUE THREAD

**Issue by lyrwang** [tseemann/shovill#47]
Hi,
I tried running shovill with the `--trusted-contigs` option under `--opts` but it returns `Unknown option: trusted-contigs`

Thanks!
Ruth

**Comment by tseemann** [comment]
You need to put all the extra spades options in quotes.
For example:
```
shovill --outdir asm --opts "--trusted-contigs other.fasta" --R1  ...
```
Otherwise Unix thinks it is meant to be an *option* to shovill rather than a *parameter* to an option.
