### ISSUE TITLE
Have you tried shovill on yeast size or aspergillus size genomes?

### ISSUE THREAD

**Issue by MichaelFokinNZ** [tseemann/shovill#48]
What is the largest haploid genome size shovill can deal with?

**Comment by andersgs** [comment]
No idea. But we would love to hear your experience with it. You may have to fiddle with RAM, though. I would say there are likely better assemblers for these larger genomes. Check out the Assemblathon 2 paper [here](https://arxiv.org/abs/1301.5406) for some ideas.

Good luck, and if you do try shovill with fungus, please let us know.

**Comment by tseemann** [comment]
If you can assemble it with Spades, you can assemble it with Shovill.

Fungus up to 50 Mbp should be ok.
