### ISSUE TITLE
Error with KMC?

### ISSUE THREAD

**Issue by ehj000** [tseemann/shovill#49]
I am interested in testing your tool, however I get an error from KMC -> 20-kmc.log:
Error: Cannot open temporary file /var/folders/c9/8b9fmkr15wd0pbzkjgjy7yv00000gp/T/kmc_00253.bin

The kmc_00253.bin does not exist (only 0-00252.bin)

I am running this on OS-X installed via Homebrew
Best, Erik

**Comment by ehj000** [comment]
It seemed to be an memory issue. I was able to run the pipeline with the same data on a different machine with 256 GB RAM.
Thank you for a great pipeline
Best, Erik

**Comment by franciscozorrilla** [comment]
Reporting some strange behavior when running `shovill`: It ran for a number of samples without any problems on my macbook. Then I tried adding the `--opts --isolate` flag to the call which caused my laptop to crash/shutdown, now I can't run `shovill` without getting this error.

```
Error: Cannot open temporary file /var/folders/py/5l6wkljj4yv_36fjm4gqgx800000gn/T/LQysOUlPuD/kmc_00253.bin
```
