### ISSUE TITLE
change behaviour of --force

### ISSUE THREAD

**Issue by schultzm** [tseemann/shovill#57]
This or similar commands (when outdir contains the reads) will delete the reads:
`shovill --outdir SRR1950887 --r1 SRR1950887/SRR1950887_1.fastq.gz --r2 SRR1950887/SRR1950887_2.fastq.gz --cpus 8 --keepfiles --force`.

As per your email, I am filing it as a feature request to only delete files in the outdir produced by shovill and not delete the reads or any other user-made files.

**Comment by tseemann** [comment]
I have removed the behaviour of nuking the whole folder - you are right this is bad.

Related to #61 and #62
