### ISSUE TITLE
Should Shovill support SE reads?

### ISSUE THREAD

**Issue by lindechun** [tseemann/shovill#58]
Should Shovill support SE reads?

**Comment by lindechun** [comment]
Should Shovill support SE reads?

**Comment by tseemann** [comment]
Do you have single-end Illumina reads for a whole genome sequencing project?

**Comment by lindechun** [comment]
nope. but i have some single-end BGISeq-500 reads.

**Comment by tseemann** [comment]
Nice!   

This is a duplicate of #43 so I'll close this and leave the original open.
