### ISSUE TITLE
Stalling after Lighter of R1 reads

### ISSUE THREAD

**Issue by PlantDr430** [tseemann/shovill#73]
Hello,

I ran the command line:

shovill --gsize 37388842 --outdir SRR6985962_out --R1 SRR6985962_1.fastq.gz --R2 SRR6985962_2.fastq.gz

Which ran for a bit and started running Lighter:

Using pilon - /usr/local/bin/pilon
Using tee - /usr/bin/tee
Using sysctl - /usr/sbin/sysctl
Machine has 24 CPU cores and 64 GB RAM
Changing into folder: /Volumes/Pegasus/WykaClavicepsGenomes/MiSeq/SRR6985962/SRR6985962_out
Collecting raw read statistics with 'seqtk'
Running: seqtk fqchk -q3 \/Volumes\/Pegasus\/WykaClavicepsGenomes\/MiSeq\/SRR6985962\/SRR6985962_1\.fastq\.gz > 10-seqtk.tab
Read stats: total_bp = 3176525780
Read stats: avg_len = 149
Read stats: max_len = 151
Read stats: min_len = 35
Using genome size 37388842 bp
Estimated sequencing depth: 84 x
No read depth reduction requested or necessary.
Running: ln -s \/Volumes\/Pegasus\/WykaClavicepsGenomes\/MiSeq\/SRR6985962\/SRR6985962_1\.fastq\.gz R1.fq.gz
Running: ln -s \/Volumes\/Pegasus\/WykaClavicepsGenomes\/MiSeq\/SRR6985962\/SRR6985962_2\.fastq\.gz R2.fq.gz
Average read length looks like 149 bp
Setting k-mer range to (31 .. 111)
Estimated K-mers: 31 51 71 91 111 [kn=5, ks=20, kmin=31, kmax=111]
Using kmers: 31,51,71,91,111
Correcting reads with 'Lighter'
Running: lighter -od . -r R1.fq.gz -r R2.fq.gz -K 32 37388842 -t 16 -maxcor 1 >> 40-lighter.log 2>&1

However, it corrected the first reads (R1), see log below:

[2018-05-07 15:22:14] =============Start====================
[2018-05-07 15:22:14] Scanning the input files to infer alpha(sampling rate)
[2018-05-07 15:22:42] Average coverage is 85.032 and alpha is 0.082
[2018-05-07 15:22:44] Bad quality threshold is "/"
[2018-05-07 15:23:21] Finish sampling kmers
[2018-05-07 15:23:21] Bloom filter A's false positive rate: 0.010524
[2018-05-07 15:24:09] Finish storing trusted kmers

But after 18 hours it has not moved on to correcting the R2 reads or even stating that it is starting to scan the R2 reads. This is also the 2nd time the pipline stalled here for several hours.

**Comment by tseemann** [comment]
You set the genome size to  `37388842` ?
That is 37 Mbp ?
Did you mean 3.7 Mbp?

You might be running out of RAM and your computer has moved to using disk swap space?

Does Spades work on your genome?

**Comment by PlantDr430** [comment]
Hmm okay. I have not tried the data on Spades or megahit yet. I recently just got it and wanted to try this pipeline. 

If you want to try again you can download the files here: https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP139610

If not, don't worry. We will try to figure something else out.

**Comment by tseemann** [comment]
@PlantDr430 Shovill just uses Spades under the hood. If you don't have enough RAM for Spades, you won't have enough RAM for Shovill.

I would do a first pass assembly with ABySS or megahit just to see if the data is ok.
