### ISSUE TITLE
Adding a "continue" option 

### ISSUE THREAD

**Issue by lambros-f** [tseemann/shovill#74]
First I would like to **thank you** for this very well documented tool!

I was wondering if it would be useful to add a "continue" option like SPAdes has to continue the analysis/assembly if you get a crash due to memory issues etc.

For example my job crashed at the Pilon step, but I don't see a way to continue from that step and not starting all over again.

**Comment by tseemann** [comment]
Given that a typical genome assembly only takes 10 minutes or less, I don't feel there is much need for `--continue`.   

Do you know why it crashed at pilon?   
Java problem?  
Or not enough RAM via `--ram` ?

**Comment by lambros-f** [comment]
Unless if you use it for eukaryotes. Then it seems to take more time (>10h) for complex 120Mb genomes. So it might be useful but I definitely agree, not absolutely necessary.

Yes the crash was due to insufficient memory allocation (my bad, fixed it).
