### ISSUE TITLE
stalled running kmc in for loop in shell 

### ISSUE THREAD

**Issue by indexofire** [tseemann/shovill#80]
when assembling multiple bacteria genomes,  I used to use for loop in terminal like this in server:

```bash
$ nohup sh -c 'for i in ...; do shovill --R1 ... --R2 ... ; done' &
```

However, the pipeline would stalled sometimes when running kmc. If I just run shovill to assemble the stalled genome, it passed kmc check, and everything is ok. My server has 128g ram and no seperated /tmp partition ( /tmp is in the / filesystem, so I think the disk space is enough). Any suggestion? Thanks

**Comment by tseemann** [comment]
The latest version (git HEAD) use `mash` instead of `kmc` .

Perhaps use:

```
nohup parallel -j 1 shovill --R1 {}_R1.fq.gz --R2 {}_R2.fq.gz --outdir {} :::: id1 id2 id3 id4
```

**Comment by indexofire** [comment]
got that, it had been updated in the master branch. thanks anyway, Hope 1.0 comes out soon.
