### ISSUE TITLE
Feature Request: Resume from failed SPAdes assembly

### ISSUE THREAD

**Issue by bstamps** [tseemann/shovill#9]
Is it possible to add a "--resume" style option to begin the workflow from SPAdes onward? Alternatively a similar option where you can specify which point to begin from.

**Comment by tseemann** [comment]
May I ask what the use-case for that is?

If you only want Spades and the correction, I would suggest just using Spades directly with `--careful` 

I could convert the pipeline into a `Makefile` however.

**Comment by tseemann** [comment]
I have decided to not implement this.

**Comment by luptior** [comment]
This feature would be useful if run really big projects which takes a long time but failed when problems like memory limit and time limit happen.
