### ISSUE TITLE
Default assembler?

### ISSUE THREAD

**Issue by thorellk** [tseemann/shovill#94]
In the readme there is an inconsistency in the Advanced options section where in the parameter overview part says `--assembler XXX Assembler: spades skesa megahit velvet (default: 'skesa')` and in the more detailed description says "By default it will use SPAdes, but you can also choose Megahit or SKESA."

**Comment by tseemann** [comment]
Thanks Kaisa!

There was a couple of other changed defaults too - i've fixed the docs.
