### ISSUE TITLE
output name option request

### ISSUE THREAD

**Issue by darwinbandoy** [tseemann/shovill#97]
Will it be possible that the input file name BCW_4567.fq.gz be integrated in the output file like BCW_4567spades.fasta? 

While it can be done using scripts like this:

for dir in $(ls -d */ | tr -d "/"); do cd $dir; mv *.* "$dir"_*.*; cd ../; done

It took me sometime figuring how to rename using input name for batch assemblies.

**Comment by tseemann** [comment]
Usually you would do this in your pipelines. 
I probably won't be adding this functionality to shovill.
This may help:

```
for ID in BCW_45 BCW_46 BCW_47 BCW_56 ; do
  shovill --outdir ${ID} --R1 ${ID}_R1.fq.gz --R2 ${ID}_R2.fq.gz
  mv ${ID}/contigs.fa ${ID}/${ID}.fna
done
```

Please note that `spades.fasta` is NOT the shovill assembly!  That is an intermediate output. You need `contigs.fa` and that is the one I rename above in the loop.

**Comment by darwinbandoy** [comment]
Thanks!
