### ISSUE TITLE
RAM 32 Gb enforced? [bug]

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/shovill#98]
Just updated to the last version via bioconda. I run it on a server with 31.37 Gb RAM (well, 32 Gb), and shovill refuses to run if I don't set RAM manually.

I think 32 Gb is a bit high as default if it is enforced. 

Why not keep it restricted to max memory reported by system?

**Comment by andersgs** [comment]
This is related to issue #35

**Comment by tseemann** [comment]
One issue with the whole thing is that Spades will often crash if CPUS > RAM due to ram per thread settings (hidden) and ulimit on number of open files.

**Comment by tseemann** [comment]
This was fixed:
```
   {OPT=>"cpus=i",     VAR=>\$cpus,      DEFAULT=>$ENV{SHOVILL_CPUS} || min(8,$CORES), DESC=>"Number of CPUs to u
    {OPT=>"ram=f",      VAR=>\$ram,       DEFAULT=>$ENV{SHOVILL_RAM} || min(16,$MEMORY),  DESC=>"Try to keep RAM u
```
