### ISSUE TITLE
Option for --threads instead of --cpus

### ISSUE THREAD

**Issue by kapsakcj** [tseemann/shovill#99]
Hi Torsten,

Thanks for developing Shovill! It will likely take the place of SPAdes in our pipelines due to how fast it can assemble. SPAdes has been the bottleneck for quite some time and the faster we can analyze the data, the better.

I went on a journey over the last couple of days and built a Docker image for Shovill 1.0.4. It seems to be pretty stable in my hands - I've successfully run about a dozen Salmonella isolates (MiSeq 250 PE reads) through using default options (except `--ram` and `--cpus`). If you'd like, you're more than welcome to link to the docker image in the README - https://hub.docker.com/r/staphb/shovill/ . I've also built docker images for [prokka](https://hub.docker.com/r/staphb/prokka/) and [abricate](https://hub.docker.com/r/staphb/abricate/) too....I'm a big fan of your software if you couldn't tell :+1: 

The image can be downloaded with `docker pull staphb/shovill:latest` or `docker pull staphb/shovill:1.0.4` if you have docker installed.

Anyways onto my request - it would be nice to have an option `--threads 0` to determine the max number of threads instead of the max number of CPU cores. I'm currently working on a VM that has 8CPU cores in total, but each core has 2 threads. When I run shovill with `--cpus 0`, it chooses 8 cores, although I have 16 threads available, and could potentially speed up the process. Obviously I can get around this by specifying `--cpus 16` but it may be useful to have the option for auto-detecting the max # of threads.

Best,
Curtis

**Comment by andersgs** [comment]
I am not sure who you have configured your entry point, but I wonder if you could max it out with: 
```
THREADS=$(grep -c process /proc/cpuinfo)
shovill --cpus $THREADS ...
```

**Comment by kapsakcj** [comment]
^ this would work.

Turns out I'm an idiot. My VM does not actually have 16 threads. Please disregard this issue.
```
$ grep -c process /proc/cpuinfo
8

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:              0
CPU MHz:               2300.000
BogoMIPS:              4600.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat arch_capabilities
```

**Comment by tseemann** [comment]
Thank you @andersgs for helping here.
It did seem weird that "threads" did not equal "cores".
I know they are different things in a technical sense, but in software they are usually synonyms.
